name: generic_shop_app_content
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/ljmatan
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_architecture:
    path: ../arch
  generic_shop_app_api:
    path: ../api
  generic_shop_app_services:
    path: ../services
  generic_shop_app_data:
    path: ../data
  flutter_svg: ^2.2.0
  webview_flutter: ^4.13.0
  flutter_map: ^8.1.1
  collection: ^1.19.1
  camera: ^0.11.1
  zxing2: ^0.2.4
  image: ^4.5.4
  cached_network_image: ^3.4.1
  flutter_auto_size_text: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dartdoc: ^8.3.4

flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 100
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 800
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900