name: generic_shop_app

publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - core/api
  - core/arch
  - core/cms
  - core/content 
  - core/data
  - core/i18n
  - core/services
  - plugins/demo 
  - plugins/fitness_tracker
  - plugins/froddo_b2b
  - plugins/froddo_b2c
  - plugins/iot
  - plugins/trading