name: generic_shop_app_services
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/ljmatan
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_api:
    path: ../api
  generic_shop_app_architecture:
    path: ../arch
  generic_shop_app_content:
    path: ../content
  url_launcher: ^6.3.1
  app_tracking_transparency: ^2.0.6
  shared_preferences: ^2.3.3
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  collection: ^1.19.1
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0