name: generic_shop_app_services
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/ljmatan
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_api:
    path: ../api
  generic_shop_app_architecture:
    path: ../arch
  url_launcher: ^6.3.1
  app_tracking_transparency: ^2.0.6
  shared_preferences: ^2.3.3
  barcode: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
