name: generic_shop_app_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  
resolution: workspace

dependencies:
  generic_shop_app_architecture:
    path: ../arch
  generic_shop_app_data:
    path: ../data
  json_annotation: ^4.9.0
  http: ^1.2.1
  encrypt: ^5.0.3
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  dartdoc: ^8.3.4
