name: generic_shop_app_architecture
description: "Basic Flutter project structure."
version: 0.0.1
homepage: https://github.com/ljmatan
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_api:
    path: ../api
  generic_shop_app_data:
    path: ../data
  generic_shop_app_services:
    path: ../services
  generic_shop_app_content:
    path: ../content
  universal_html: ^2.2.4
  http: ^1.3.0
  source_gen: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14