name: generic_shop_app_architecture
description: "Basic Flutter project structure."
version: 0.0.1
homepage: https://github.com/ljmatan
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_api:
    path: ../api
  generic_shop_app_content:
    path: ../content
  generic_shop_app_data:
    path: ../data
  generic_shop_app_plugin:
    path: ../plugin
  generic_shop_app_services:
    path: ../services
  http: ^1.3.0
  source_gen: ^2.0.0
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  dartdoc: ^8.3.4