name: generic_shop_app_demo
description: "Generic Shop App Project Demo Showcase."
version: 0.0.1
homepage: https://github.com/ljmatan
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: '>=3.3.0'
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_architecture:
    path: ../arch
  generic_shop_app_fitness_tracker:
    path: ../../plugins/fitness_tracker
  generic_shop_app_froddo_b2b:
    path: ../../plugins/froddo_b2b
  generic_shop_app_froddo_b2c:
    path: ../../plugins/froddo_b2c
  device_frame_plus: ^1.5.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/fitness_tracker/
    - assets/froddo_b2b/
    - assets/froddo_b2b/svg/
    - assets/froddo_b2c/
    - assets/froddo_b2c/svg/
    
  # fonts:
  #   - family: Comic Neue
  #     fonts:
  #       - asset: assets/fonts/ComicNeue-Light.ttf
  #         weight: 100
  #       - asset: assets/fonts/ComicNeue-Light.ttf
  #         weight: 200
  #       - asset: assets/fonts/ComicNeue-Regular.ttf
  #         weight: 300
  #       - asset: assets/fonts/ComicNeue-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/ComicNeue-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/ComicNeue-Regular.ttf
  #         weight: 600
  #       - asset: assets/fonts/ComicNeue-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/ComicNeue-Bold.ttf
  #         weight: 800
  #       - asset: assets/fonts/ComicNeue-Bold.ttf
  #         weight: 900
  #   - family: Quicksand
  #     fonts:
  #       - asset: assets/fonts/Quicksand-Light.ttf
  #         weight: 100
  #       - asset: assets/fonts/Quicksand-Light.ttf
  #         weight: 200
  #       - asset: assets/fonts/Quicksand-Medium.ttf
  #         weight: 300
  #       - asset: assets/fonts/Quicksand-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Quicksand-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/Quicksand-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Quicksand-SemiBold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Quicksand-Bold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Quicksand-Bold.ttf
  #         weight: 900
  #   - family: Merriweather Sans
  #     fonts:
  #       - asset: assets/froddo_b2c/fonts/MerriweatherSans-VariableFont_wght.ttf
  #   - family: Open Sans
  #     fonts:
  #       - asset: assets/fitness_tracker/fonts/OpenSans-VariableFont_wdth,wght.ttf
