name: middleware
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  generic_shop_app_api:
    path: ../core/api
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  mongo_dart: ^0.10.2
  pool: ^1.5.1

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
