name: generic_shop_app_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_architecture:
    path: ../plugins/arch
  http: ^1.2.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.0
